name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make deps
      run: make -C src deps TARGET=agent
    - name: make check
      run: make -C src TARGET=agent
